import '../fonts/font_faces.css';
export default {
  fonts: {
    title: 'todo-title',
  },
  colors: {
    text: '#000',
    background: '#fff',
    primary: '#33e',
    panel: '#bad5ff',
  },
  sizes: {
    todoWidth: '600px',
    xxxl: '48px',
    xxl: '28px',
    xl: '20px',
    l: '14px',
    m: '12px',
    s: '10px',
    xs: '8px',
    xxs: '6px',
    xxxs: '4px',
    xxxxs: '3px',
  },
  space: {
    xxxl: '48px',
    xxl: '28px',
    xl: '20px',
    l: '14px',
    m: '12px',
    s: '10px',
    xs: '8px',
    xxs: '6px',
    xxxs: '4px',
    xxxxs: '3px',
  },
  fontSizes: {
    xxxxxxl: '60px',
    xxxxxl: '50px',
    xxxxl: '40px',
    xxxl: '32px',
    xxl: '26px',
    xl: '24px',
    l: '20px',
    m: '15px',
    s: '14px',
    xs: '12px',
    xxs: '10px',
  },
  borderWidths: {
    xxl: '12px',
    xl: '10px',
    l: '8px',
    m: '6px',
    s: '4px',
    xs: '2px',
    xxs: '1px',
  },
  radii: {
    l: '10px',
    m: '4px',
    s: '2px',
  },
};
